spring.application.name=auth-service
spring.profiles.default=local
server.port=${PORT:8085}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:o3zRbRLwQm4gwsueqP2s2PLxKpPOgZX8y6q8AZNFMl4=}


#spring.profiles.active=docker
