spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/payment}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Garima@123}
spring.datasource.driver-class-name=org.postgresql.Driver
