spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/order}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Garima@123}
spring.datasource.driver-class-name=org.postgresql.Driver

customerServiceUrl=${CUSTOMER_SERVICE_URL:http://customer-service:8080/customer}
productServiceUrl=${PRODUCT_SERVICE_URL:http://product-service:8083/product}
