spring.application.name=order-service
spring.profiles.default=local
server.port=${PORT:8081}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

#spring.profiles.active=docker
